spring:
  # 配置文件上传大小限制
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
minio:
  host: http://47.109.79.50:9000
  url: ${minio.host}/${minio.bucket}/
  access-key: minioadmin
  secret-key: Liyan@9802
  bucket: test
